CREATE TABLE schedule (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    todo VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);